# Generated by Django 3.1 on 2021-07-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_prductgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrductGallery',
            new_name='ProductGallery',
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
