# Generated by Django 3.1 on 2021-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210626_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
