# Generated by Django 3.1 on 2021-06-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='order_note',
        ),
    ]
