# Generated by Django 3.1 on 2021-06-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profession',
            field=models.CharField(blank=True, max_length=210),
        ),
    ]
