# Generated by Django 3.1 on 2021-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='bugambilaya.jpeg', null=True, upload_to='userprofile/'),
        ),
    ]
