# Generated by Django 3.1 on 2021-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
