# Generated by Django 3.1 on 2021-06-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip',
            field=models.IntegerField(default='', null=True),
        ),
    ]
