# Generated by Django 3.1 on 2021-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210630_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
