# Generated by Django 3.1 on 2021-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userprofile/bugambilaya.jpg', null=True, upload_to='userprofile/'),
        ),
    ]
