# Generated by Django 3.1 on 2021-07-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210701_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, default='Philippines', max_length=54),
        ),
    ]
